correct some typos
prawnpdf/prawn pull request #1366
Opened 2024-12-13 12:42 UTC by defkode

2024-12-13 21:05 UTC, gettalong requested changes
Thanks for the corrections!

Please fix the one correction, everything else looks good!

2024-12-13 21:05 UTC, gettalong commented on spec/prawn_manual_spec.rb
> +    # decompressed just fine, but for whatever reason, compression produces
The comma should be after "but" not before.

2024-12-14 08:57 UTC, pointlessone commented
@defkode Thank you. What software did you use for this PR?

2024-12-14 09:42 UTC, defkode commented
> @defkode Thank you. What software did you use for this PR?

I spotted some typos when working with the manual, and then run https://github.com/crate-ci/typos to check if there's more.

2024-12-14 10:02 UTC, defkode commented
@pointlessone I left Rubocop's offences intact (probably `Style/AccessModifierDeclarations` to be excluded?)

Thanks for great software 👍🏻

2024-12-17 08:41 UTC, gettalong approved these changes

2024-12-17 08:41 UTC, gettalong approved these changes

2025-01-17 11:08 UTC, closed without merging